# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_AS:   [ROLE_ADMIN]
        ROLE_API:  [ROLE_API]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path: /api/login_check
                require_previous_session: false
                username_parameter: username
                password_parameter: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        register:
            pattern:   ^/api/register
            stateless: true
            anonymous: true
        contact:
            pattern:   ^/api/contact
            stateless: true
            anonymous: true
        doc:
            pattern:   ^/api/doc
            stateless: true
            anonymous: true
        api:
            pattern:   ^/api
            stateless: true
            lexik_jwt:
                authorization_header:
                    enabled: true
                    prefix:  Bearer
                query_parameter:
                    enabled: true
                    name:    bearer
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            logout:       true
            anonymous:    true
            
    access_control:
        - { path: ^/api/doc,        role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register,   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/contact,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api,            role: IS_AUTHENTICATED_FULLY }